publish_to: none

name: permissions
description: Checking and requesting device permissions
version: 0.3.0
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: nl.unlockagency.permissions
        pluginClass: PermissionHandlingPlugin
      ios:
        pluginClass: PermissionHandlingPlugin
